pipeline {
    agent any
    
    stages {
        stage('Build') {
            steps {
              dir('transfer-service-ci-demo/api-tests')  {
                 sh 'mvn clean test-compile'
              }
            }
        }
        stage('Test') {
            steps {
              dir('transfer-service-ci-demo/api-tests')  {
                 sh 'mvn test'
              }
            }
        }
    }
}